# Generated by Django 3.1.13 on 2022-02-21 13:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kboplayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(choices=[('nc', 'NC'), ('doosan', '두산'), ('kia', 'KIA'), ('kt', 'KT'), ('hanhwa', '한화'), ('lg', 'LG'), ('ssg', 'SSG'), ('lotte', '롯데'), ('kiwoom', '키움')], default=None, max_length=10)),
                ('position', models.CharField(choices=[('투수', '투수'), ('타자', '타자')], default=None, max_length=5)),
                ('year_money', models.CharField(max_length=1000, null=True)),
                ('year', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('attack_or_attacked', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('순위', models.TextField(blank=True, null=True)),
                ('선수명', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('팀명', models.TextField(blank=True, null=True)),
                ('avg', models.TextField(blank=True, db_column='AVG', null=True)),
                ('g', models.TextField(blank=True, db_column='G', null=True)),
                ('pa', models.TextField(blank=True, db_column='PA', null=True)),
                ('ab', models.TextField(blank=True, db_column='AB', null=True)),
                ('r', models.TextField(blank=True, db_column='R', null=True)),
                ('h', models.TextField(blank=True, db_column='H', null=True)),
                ('number_2b', models.TextField(blank=True, db_column='2B', null=True)),
                ('number_3b', models.TextField(blank=True, db_column='3B', null=True)),
                ('hr', models.TextField(blank=True, db_column='HR', null=True)),
                ('tb', models.TextField(blank=True, db_column='TB', null=True)),
                ('rbi', models.TextField(blank=True, db_column='RBI', null=True)),
                ('sac', models.TextField(blank=True, db_column='SAC', null=True)),
                ('sf', models.TextField(blank=True, db_column='SF', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 2, 21, 13, 39, 22, 116304, tzinfo=utc))),
                ('player_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kbo_player.kboplayer')),
            ],
        ),
    ]
