# Generated by Django 3.1.13 on 2022-02-17 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kboplayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(choices=[('nc', 'NC'), ('doosan', '두산'), ('kia', 'KIA'), ('kt', 'KT'), ('hanhwa', '한화'), ('lg', 'LG'), ('ssg', 'SSG'), ('lotte', '롯데'), ('kiwoom', '키움')], default=None, max_length=10)),
                ('position', models.CharField(choices=[('투수', '투수'), ('타자', '타자')], default=None, max_length=5)),
                ('year_money', models.CharField(max_length=1000, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
