# Generated by Django 3.1.13 on 2022-02-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbo_player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kboplayer',
            name='team',
            field=models.CharField(choices=[('nc', 'NC'), ('doosan', '두산'), ('kia', 'KIA'), ('kt', 'KT'), ('hanhwa', '한화'), ('lg', 'LG'), ('ssg', 'SSG'), ('lotte', '롯데'), ('kiwoom', '키움')], default=None, max_length=10),
        ),
    ]
