# Generated by Django 3.1.13 on 2022-02-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbo_player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kboplayer',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
