# Generated by Django 3.1.13 on 2022-02-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbo_player', '0002_kboplayer_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='kboplayer',
            name='attack_or_attacked',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
