# Generated by Django 3.1.13 on 2022-02-17 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbo_player', '0009_auto_20220217_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kboplayer',
            name='year',
        ),
    ]
