# Generated by Django 3.1.13 on 2022-02-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbo_player', '0010_remove_kboplayer_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='kboplayer',
            name='year',
            field=models.CharField(choices=[('2021년', '2021년'), ('2020년', '2020년'), ('2019년', '2019년')], max_length=10, null=True),
        ),
    ]
